### PR TITLE
Implement disk control/m3u support

### PR DESCRIPTION
**Pull request by ChrisRx**
This is resubmitted from PR #76.  It had diverged so much it was difficult to update and it was easier to just close the previous PR and resubmit.

### CODE REVIEW

**Comment by twinaphex** [comment]
Thanks,

@trapexit Can this be merged? This is an important feature that people want.

**Comment by trapexit** [comment]
Looks like the commits should be collapsed but I need to take a look / test it out. I'll try to get to it today.

**Comment by trapexit** [comment]
This only manages the changing of discs? It doesn't reset the system so what's the workflow for the user?

**Comment by ChrisRx** [comment]
The user opens the retroarch menu, navigates to Disk Control and toggles `Disk Cycle Tray Status`. Once the virtual disk is in an ejected state, the user uses `Disk Index` to set the index of the disks defined in the m3u file.  Finally, the user closes the disk by toggling `Disk Cycle Tray Status` again.  It should also reset the system [here](https://github.com/ChrisRx/4do-libretro/blob/master/disk_control.c#L35) via the libretro API call to `retro_reset()`.

**Comment by ChrisRx** [comment]
Is there anything additional that I need to do to this PR for it to be accepted?  I see other stuff was accepted to master since I last checked-in.

**Comment by ChrisRx** [comment]
At the time I wrote it some months ago the code in the repo was incredibly inconsistent (I tried to match it, but there wasn't anything consistent enough to match).  There also doesn't appear to be quorum of style between the work here for 4do and the rest of the libretro library.  With that said, if there is an accepted style I will conform to it, however, there doesn't appear to be one listed and the source code has been influx too much to derive a style since the time I started writing this functionality.  

I would also ask that you either accept this sooner rather than later, or start rebasing with master yourself (I clicked allow maintainers to edit the PR for this reason) for the time when you are ready to look over it (instead of waiting on me to do so, since I don't know when you will be ready to look at it).  Thanks.

**Comment by trapexit** [comment]
I wasn't referring to the rest of 4do but the patch itself. Some functions have return values defined on the same line and others not. Some use underscores like 4do's code now does and others not. But as I said it's fine. I'll fix it up later as with any rebasing. I'm happy to do it I just need to find the time as I mentioned.

**Comment by altiereslima** [comment]
It's good that you, trapexit, are giving continuity to 4do, since the project is abandoned.

**Comment by twinaphex** [comment]
Hi @trapexit,

can we fast-track merging this PR? Just to keep it fair also to the guy who sent this PR.
If there are still roadblocks to overcome, then let's get those fixed so we can get this PR incorporated.

**Comment by trapexit** [comment]
I was waiting for the refactor mentioned above. I can look into doing it myself in the next week or so.

**Comment by ChrisRx** [comment]
I apologize, that was my mistake, I had intended to circle back and fix the styling but completely forgot to do so and let it slip through the cracks.  I'm traveling at the moment and not able to do so, so if it isn't much trouble for you to do that would be appreciated greatly.  Sorry again for not following up, and thank you for your help and patience.

**Comment by klepp0906** [comment]
did this ever end up making it through/live?

**Comment by twinaphex** [comment]
@trapexit Please comment on this. We should either implement it or roll our own implementation if it's better then.

**Comment by trapexit** [comment]
It's not ideal because as I recall it can't detect when the disk is needed you just choose the new image and it resets the emu. It's probably fine but the code need some reworking.

**Comment by klepp0906** [comment]
so, pre-apologies if this is me being a nag, or ungrateful user.   I dont know the order of things - nor etiquette in this situation.

Ultimately just me being annoying in hopes that this doesnt fall under the pile and disappear till the end of time.

its the final system that retroarch emulates (discarding the newly added ps2) that doesnt have multi disc support implemented.   So im eager to finalize the playlist clutter and be done with it :)

been a few months so i figured id do some begging etc ;p

**Comment by trapexit** [comment]
The original author was going to make some changes so I was waiting for that. That said the new physical cdrom feature has caused this code to no longer be mergable and need to be redone. 

That said... the 3DO doesn't really understand multiple disks. Each disk is technically it's own program and the system reboots when disks changed. There isn't a real way to know a disk needs to be changed AFAIK. The patch I believe required you to exit to the menu and change the disk which then rebooted the emulator which isn't terribly different from going to the menu and picking a different game. I agree it's probably logically a bit nicer but you'll need to be generating your own playlists for 3DO either way so it's not even easier in that sense.

I'm not saying it can't or won't be done. Just that it seems not as useful as other platforms and for myself I've just been busy with other projects so I've not had the time to setup the libretro dev environment again and rewrite this patch.

**Comment by klepp0906** [comment]
understood.  thank you for replying so quickly.  I did not realize it wasnt a conventional disc-swap persay.  Was never any urgency or hurry - just curious.   Now i know :)

**Comment by trapexit** [comment]
No problem. If I could tell from within system that the game requested a game change that'd absolutely be cool and useful but I don't believe there is. The game (likely) saves state into nvram and then tells the user to replace the disk which triggers a system reboot. It's possible there is more to it (haven't fooled with a FZ-10) but the FZ-1 and Sanyo seem to reboot on eject. When I get time I'll look into more.

**Comment by klepp0906** [comment]
that would be spectacular.  I know you guys have lives too, and even without taking that into consideration, the list is long and ever growing.

please keep me posted though - whenever it does come to pass.    Thanks for your work <3

**Comment by marph43** [comment]
Hi guys
Just wanted to tell, that I would highly appreciate this feature as well.
Thanks in advance!

**Comment by soredake** [comment]
Any progress?

**Comment by trapexit** [comment]
No. If changes were made you'd see them in this PR.

The ability to emulate actual disk swapping isn't known yet. Most 3DO games just seem to expect you to insert the other disk and restart which is what this patch mostly did which isn't functionally different from just selecting the other cd image as you normally would. So this feature can be added but it won't save much time nor be automatic.

**Comment by marph43** [comment]
OK. So it should already now be possible to play a multi-game 3DO-game with Retroarch? Can you pleae tell me how I can change a disc file without resettting the running game?

**Comment by trapexit** [comment]
What game are you talking about. The multidisc games I've played save to NVRAM and you can simply boot the other disk when it asks to change disks. As I recall on my FZ-1 the open/closing of the tray resets the system.

**Comment by trapexit** [comment]
Regardless, if a game somehow keeps the system from restarting on disk changes... that hardware feature is not yet known so we couldn't "fix" it at the moment. This PR is simply changing the disk and restarting the emulation. Literally the same as selecting the other disk from the normal menu.

**Comment by marph43** [comment]
@trapexit : I am talking about "The Daedalus Encounter". It's a 4 disc game and requires to change the discs frequently. I never played it on the original hardware, so I don't know if it manages a disc change without resetting the system, but it very much looks like it.
Anyways. It would be great if it could be played somehow with Retroarch. Thnaks in advance for your work!

**Comment by trapexit** [comment]
It seems to play fine to me by simply restarting with the disk in question when asked.

**Comment by Sanaki** [comment]
In light of the damage from the hack, this may need to be reopened as a new PR, not sure.

**Comment by twinaphex** [comment]
HI there, I'm putting this back on my radar. I will probably try to reimplement it and this time get it fast tracked.

**Comment by trapexit** [comment]
Without proper emulation of the actual cdrom change disk hardware this can't be more than changing the image and then rebooting the system.

**Pull request closed without merging**
